[pytest]
addopts =
    -v
    --strict-markers
    --alluredir=allure-results
    --clean-alluredir
    --capture=no
    --log-cli-level=INFO
    --log-date-format="%Y-%m-%d %H:%M:%S"
    --log-format="%(asctime)s %(levelname)s %(message)s"

markers =
    api: API tests
    ui: UI tests
    mobile: Mobile tests
    smoke: Smoke tests
    regression: Regression tests
    critical: Critical severity
    major: Major severity
    minor: Minor severity

testpaths = api/tests ui/tests mobile/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
